POST http://localhost:3001/error HTTP/1.1
content-type: application/json

{
    "email": "about-yy@gmail.com@gmail.com",
    "password": "Hao8Nadew"
}

####

POST http://localhost:3001/user/regist HTTP/1.1
content-type: application/json

{
    "email": "abouta-yy@gmail.com@gmail.com",
    "password": "Hao8Nadew"
}

###
GET http://localhost:3001/error 