version: "3.8"
services: 
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app/:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDIR_USEPOLLING=true
      - PORT=3000
    tty: true
    ports: 
      - "3000:3000"
    command: npm run dev

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app/:/app
    tty: true
    env_file:
      - ./backend/app/.env
    environment:
      - PORT=3001
      - TZ=Asia/Tokyo
    ports: 
      - "3001:3001"
    command: npm run dev:watch

  mysql: 
    container_name: mysql
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    ports: 
      - 3306:3306
    env_file:
      - ./mysql/.env_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    