version: "3.8"
services: 
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app/:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDIR_USEPOLLING=true
    tty: true
    ports: 
      - "3000:3000"
      - "5173:5173"
    command: npm run dev
